### ISSUE TITLE
Require payu version

### ISSUE THREAD

**Issue by aidanheerdegen** [payu-org/payu#147]
Since the issue with some buggy versions, how about adding a minimum version requirement?

I can see this is also useful when doing things like changing the collate config layout, so it is no longer compatible with earlier versions. So have a config flag that sets the minimum version required?

This is most useful for @nichannah and @aekiss when creating configs for COSIMA that will be widely shared. It allows them to use the latest features and be confident that they will be supported by the payu version someone is running, or tell them to upgrade.

**Comment by marshallward** [comment]
Do you mean models requiring a minimum version?

**Comment by marshallward** [comment]
Or do you mean adding a minimum version to the config.yaml?

**Comment by marshallward** [comment]
Also, I totally support this, but I think our current practices do not make this easy.

For example, if for, say, OM2, version 1.3.2 works but 1.3.3 breaks it, then we need to start doing things in a way that permits updates to older versions.  i.e. we might need to bone up on [git-flow](https://nvie.com/posts/a-successful-git-branching-model/).

1) Track versions as branches
2) Define versions more tightly: a.b.c where a is an API change, b is features, and c are bugfixes
3) Stricter versioning: We support, say, 1.3 but do not specify a 1.3.x version.

I'm not sure we are operating in a way that supports this more formal approach, so it's something to think about.

Having said all that, we could just specify versions and not worry about the (generally minor) contradictions that could emerge.

**Comment by aidanheerdegen** [comment]
Minimum version to `config.yaml`. As I say, of most utility for those sharing configs.

What you suggest above is an absolute version spec, like `conda`. Which still doesn't necessarily mean back-porting fixes to older versions IMO. 

In any case I'm just suggesting a minimum version, which certainly doesn't necessitate keeping live branches of versions.

**Comment by marshallward** [comment]
I see, so we only say the oldest version for which it works. Not that it works for every version afterwards.  Is that right?

**Comment by aidanheerdegen** [comment]
Yeah, that was the idea. 

It came specifically from noticing that the COSIMA configs are using the old collate config syntax, and thinking they should be updated, but it might stuff a lot of people around. If only the config could specify a minimum payu version ... 

But it means payu has to store it's version inside itself. Good luck with that.

**Comment by marshallward** [comment]
You mean something other than `payu.__version__` ?

**Comment by aidanheerdegen** [comment]
Probably not. How do you get that in there without altering the git hash, which means a new tag which means .... <head falls off>

**Comment by anton-seaice** [comment]
This gets an upvote from me. We are now doing OM3 development, but the issues are similar :)
