### ISSUE TITLE
Specify loader in yaml.load(config_file)

### ISSUE THREAD

**Issue by HoWol76** [payu-org/payu#175]
Getting a warning when running payu:

> /g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.01/lib/python3.6/site-packages/payu/fsops.py:45: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
> config = yaml.load(config_file)

Seems they expect something like 

`config = yaml.load(config_file, Loader=yaml.FullLoader)`

**Comment by aidanheerdegen** [comment]
I'll merge it when I've tested it if that is ok
