### ISSUE TITLE
shortpath --> scratchpath

### ISSUE THREAD

**Issue by navidcy** [payu-org/payu#224]
`shortpath` is deprecated with new gadi machine.
Perhaps change it to `scratchpath` or make a synonym to retain backwards compatibility?

**Comment by navidcy** [comment]
Is it time to let go of `shortpath`?

**Comment by aidanheerdegen** [comment]
I could have sworn we'd had a discussion about this already, but if we had it isn't in the issues or PRs.

I think the argument was that there were a lot of legacy configs that already use `shortpath`, and that it could potentially be just as confusing adding `scratchpath` as leaving it as-is.

**Comment by navidcy** [comment]
That’s why I suggested a synonym, ie both should work. Feel free to close the issue if discussion was made : )

**Comment by aekiss** [comment]
or maybe a neutral synonym like `outputpath` that's independent of whatever NCI decide to call their scratch space? Who knows what it will be called in the next machine...

**Comment by navidcy** [comment]
@aekiss looks ahead in the future.

**Comment by aidanheerdegen** [comment]
In a way `shortpath` is already machine agnostic, as there is no longer a `/short` filesystem ... the argument against change is confusion. It sort of doesn't matter what you choose as your new name, it will still be confusing that there are now two names for the same thing, but not sure I'm a fan of `outputpath`. We already have `output000` directories, and the `laboratory` contains more than just outputs.

`labprefix` is possibly the most accurate, but isn't intuitive.

**Comment by aekiss** [comment]
I'm happy to keep `shortpath`, with no synonyms. I haven't heard of anyone being confused by it, whereas 2 names for the same thing is bound to cause confusion.

**Comment by navidcy** [comment]
Let’s keep it. It’s OK :)
Sorry for creating noise. We have much more pressing things we can deal with, eg, climate change?
