### ISSUE TITLE
Add option to overwrite existing directories

### ISSUE THREAD

**Issue by aidanheerdegen** [payu-org/payu#255]
Users would like to be able to `payu run` with an existing `work` directory and for `payu` to run as usual, removing the `work` directory automatically.

There are some issues with implementing this interactively (#250) so a half way solution is to provide a command line argument to remove any existing `work` directory. The option `-f/--force` is probably appropriate, unless this is to broad and might want to be used in some other context?

If there is an option to overwrite an existing `work` directory should there also be an option to overwrite an existing `outputXXX` directory?

If yes then should they be separate options? Say `-w` for overwrite `work` and `-o` for overwrite `outputXXX`?

**Comment by aidanheerdegen** [comment]
What say you @marshallward?

**Comment by marshallward** [comment]
Overwriting an output feels a bit dangerous to me, but it sounds like there may be some demand for it?

But I think some sort of 'forced' run could be useful.  It's a deliberate action so users know what they're getting into.

**Comment by aidanheerdegen** [comment]
Any feels on the specific option? `-f/--force` ok with you?

**Comment by marshallward** [comment]
Yep I like it!

**Comment by aidanheerdegen** [comment]
There is a bug in the PR, I forgot to save that force argument in an environment variable so `payu run` isn't respecting it. Will fix.

**Comment by aidanheerdegen** [comment]
Forgot to add documentation!
