### ISSUE TITLE
Issue with manual collating restarts in latest payu

### ISSUE THREAD

**Issue by rmholmes** [payu-org/payu#268]
When attempting to manually collate restarts I encounter problems using the latest payu (from `conda/analysis3-20.04(analysis3-unstable)`):
```
[rmh561@gadi-login-03 01deg_jra55_ryf]$ pwd
/home/561/rmh561/access-om2/01deg_jra55_ryf
[rmh561@gadi-login-03 01deg_jra55_ryf]$ payu collate --directory=archive/restart643/ocean/^C
[rmh561@gadi-login-03 01deg_jra55_ryf]$ cat 01deg_jra55_r_c.o5869025
laboratory path:  archive/restart643/ocean
binary path:  archive/restart643/ocean/bin
input path:  archive/restart643/ocean/input
work path:  archive/restart643/ocean/work
archive path:  archive/restart643/ocean/archive
payu: Found modules in /opt/Modules/v4.3.0
{'archive/restart643/ocean/archive/01deg_jra55_ryf/output000/ocean': []}
...
```
It looks like it's getting all those paths wrong for some reason (not picking up `shortpath` in `config.yaml`?). I have no problems if I revert to `conda/analysis3-20.01(analysis3:default)` (in which case it correctly finds `laboratory path:  /scratch/e14/rmh561/access-om2`).

**Comment by aidanheerdegen** [comment]
Thanks @rmholmes. I have reproduced. Will investigate and push a fix when I figure out the problem.

**Comment by aidanheerdegen** [comment]
The updated version (1.0.19) has been installed into `conda/analysis3-20.04(analysis3-unstable)`.

I tested it, but please let me know if it has fixed your issue @rmholmes

**Comment by rmholmes** [comment]
Thanks Aidan. Yes I just tested and it seems to work fine now.
