### ISSUE TITLE
Drop python 2.7 CI support

### ISSUE THREAD

**Issue by aidanheerdegen** [payu-org/payu#278]
The latest CI errored. I think it is just a glitch and needs to be manually re-run, but I don't have permissions to do so it seems

https://travis-ci.org/github/payu-org/payu/jobs/723678770

Also in that log was this:

> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

I think we should just drop `python27` from the CI as it is old and crufty. If someone really needs it and we've made a breaking change they can always go back and use an older version. Could tag a release as last known good with `python27`

**Comment by marshallward** [comment]
Yes that should be fine.  I think we both still rely on systems where 2.7 remains the system default, but I guess we can deal with that in our own ways.

You really ought to have full permissions here though, I'll see why that is not the case.

**Comment by marshallward** [comment]
I wonder if the permission thing is a travis.org/travis.com transitional issue, that may be something we need to look into.

**Comment by aidanheerdegen** [comment]
Yeah I can access that now, thanks.

**Comment by aidanheerdegen** [comment]
Smashing CI issues since forever

https://github.com/payu-org/payu/commit/4dc4a2b2d431b337a55743ee1c870edced3c0e2a
