### ISSUE TITLE
readthedocs points at the wrong repo

### ISSUE THREAD

**Issue by aidanheerdegen** [payu-org/payu#279]
Since creating a new fork of `payu` at the 

https://github.com/marshallward/payu

the documentation: 

https://payu.readthedocs.io

is building from the wrong repo and not picking up changes I have made like https://github.com/payu-org/payu/commit/82e5eefb9c7d47e86fbf05aeeb227fc764a00696

**Comment by marshallward** [comment]
I have updated the URL, should update the docs shortly.

**Comment by marshallward** [comment]
Also looks like you are a maintainer.
