### ISSUE TITLE
Travis CI is moving to charging model

### ISSUE THREAD

**Issue by aidanheerdegen** [payu-org/payu#286]
Travis CI is moving to a model of charging for services. CI should be moved to a different provider. Options are CircleCI or Github Actions. I favour the latter, and will work up a PR for this.

**Comment by marshallward** [comment]
MOM6 and f90nml (as of tday) are both on GitHub Actions.  So far so good?

**Comment by aidanheerdegen** [comment]
Yeah I've done a few of the COSIMA repos already and seems to work fine, just taking me a while to get to grips with syntax changes
