### ISSUE TITLE
Docs don't have correct instructions for setting environment variables

### ISSUE THREAD

**Issue by aidanheerdegen** [payu-org/payu#308]
Docs list `ompi` option for setting environment variables

https://github.com/payu-org/payu/blame/master/docs/source/config.rst#L403-L410

as far as I can tell that option was renamed `mpi` here

https://github.com/payu-org/payu/commit/8aef1c9683d0cdf8a1deaab8e903402d70eab62a

**Comment by marshallward** [comment]
I guess `ompi` was a legacy flag.  I have no memory of it.  It may have been a dirty way to set `OMPI_*` environment variables to control MPI jobs.

I suspect you could just use `env` now in `config.yaml`:
```
env:
    UCX_LOG_LEVEL: 'error'
```

**Comment by aidanheerdegen** [comment]
Yeah that works, just need to update the docs to reflect it.

Guess how I found this out.

**Comment by aidanheerdegen** [comment]
(I can see from your suggestion that you already know)

**Comment by aidanheerdegen** [comment]
Related issue #347
