### ISSUE TITLE
`payu run` shouldn’t force changed to be tracked in git

### ISSUE THREAD

**Issue by talidemestre** [payu-org/payu#328]
Hi,

I’m trying to run many climate models as part of a pipeline, and compile the results. These models all need to be run from temporary directories, which are either not in a repository or are in a gitignored directory.

This gives me the warning
`
The following paths are ignored by one of your .gitignore files:
temp_folder
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
`
Which then crashes payu due to non zero exit code from git.

I couldn’t figure out a way to disable this behaviour with config or with some flag. Is there something I’m missing?

Thanks, Tali

**Comment by aidanheerdegen** [comment]
You want
```yaml
runlog: False
```
which should be documented, but isn't. 

So thanks for pointing that out, and sorry if that has been a PITA.

**Comment by aekiss** [comment]
Hi Tali,

Setting `runlog: false` in your config.yaml should fix this.

Also, if you are running en ensemble of climate models you might find this approach useful, which clones each of the perturbations into a separate repo and branch https://github.com/aekiss/ensemble

**Comment by aekiss** [comment]
snap!

**Comment by talidemestre** [comment]
Thanks all! That seems to have resolved that error.
