### ISSUE TITLE
Add CESM model?

### ISSUE THREAD

**Issue by dougiesquire** [payu-org/payu#331]
I've been mucking around with some CESM configurations and have ported some to payu as part of this. I've added a `Cesm` model to my own payu fork that **should** support CESM configurations run with NUOPC-CMEPS, see https://github.com/dougiesquire/payu/tree/cesm_cmeps.

The implementation probably needs some work, but I'm using it to run the following CESM configurations:
- "GMOM_JRA" (MOM6-CICE6-DATM-DROF-SLND-SWAV-SGLC): https://github.com/dougiesquire/gmom_jra
- "GMOM_JRA_WD" (MOM6-CICE6-WW3-DATM-DROF-SLND-SGLC): https://github.com/dougiesquire/gmom_jra_wd

Is there interest in a PR to add the `Cesm` model?

**Comment by aidanheerdegen** [comment]
Nice work @dougiesquire 

Is this going to be necessary to run ACCESS-OM3 with the CMEPS nuopc coupler?

Would it be correct to call this a CMEPS driver?

**Comment by dougiesquire** [comment]
I think this is quite specific to the CESM usage/implementation of CMEPS. I don't think we know yet whether the ACCESS implementation will be similar or different.

To be clear, I'm very happy just to keep this in my own fork for now and to wait until we better understanding of ACCESS+CMEPS models.

**Comment by dougiesquire** [comment]
In the COSIMA technical working group today it came up that folks would like to try and play with configurations that use this driver (without having to use my Payu fork), so I'll go ahead and submit a PR

**Comment by aekiss** [comment]
Thanks @dougiesquire I think we've [probably settled on the CESM driver for ACCESS-OM3](https://github.com/COSIMA/access-om3/discussions/13) so hopefully the driver (and your configs) will work with what we're building [here](https://github.com/COSIMA/access-om3/).

**Comment by dougiesquire** [comment]
Closed by #333

**Comment by aekiss** [comment]
Thanks for this @dougiesquire. Should this version of payu be put into `analysis3-unstable`?

**Comment by dougiesquire** [comment]
I don't see why not, but we'll need to address #339 first
