### ISSUE TITLE
conda publishing is broken

### ISSUE THREAD

**Issue by aidanheerdegen** [payu-org/payu#339]
Packaging with `conda` is done with CircleCI and it is broken

https://app.circleci.com/pipelines/github/payu-org/payu/347/workflows/e1f3f132-7569-4858-b50a-cdb36996e2d8

I'd suggest we move to using GitHub workflows, and publish to the ACCESS-NRI channel as a longer term more stable location.

@dougiesquire recently did this for intake-data frame-catalog and it should be pretty straightforward to adapt for `payu`

https://github.com/ACCESS-NRI/intake-dataframe-catalog/blob/main/.github/workflows/cd.yml

**Comment by dougiesquire** [comment]
> publish to the ACCESS-NRI channel

Is there a good way to let users know about this change? I guess most users are using the hh5 conda env and don't need to know?

Do we also want to publish to PyPI?

**Comment by aidanheerdegen** [comment]
> > publish to the ACCESS-NRI channel
> 
> Is there a good way to let users know about this change? I guess most users are using the hh5 conda env and don't need to know?

Yes. I don't personally know of anyone installing it directly, but that is something I hadn't considered.

> Do we also want to publish to PyPI?

I've never thought it was a good fit for wider/general distribution until it was more platform independent: it isn't fair on the user and would be too big a support burden. However platform independence has been an aspiration, but the resourcing and pressing use case haven't coalesced, but that may change soon. Until then I don't think PyPI is a priority.

**Comment by dougiesquire** [comment]
> I don't personally know of anyone installing it directly, but that is something I hadn't considered.

I think Chris Chapman and colleagues are trying to use it on Pawsey, but I can probably walk down the hall and tell them to change their conda channel...

**Comment by aidanheerdegen** [comment]
> I think Chris Chapman and colleagues are trying to use it on Pawsey

Good point. I assisted Chris with this, so should have considered it. 

My recollection is that they have to use a special branch that isn't merged yet (https://github.com/payu-org/payu/issues/323#issuecomment-1138155994), so probably aren't using a `conda` published version as yet. Is that right @ChrisC28?

**Comment by ChrisC28** [comment]
We are using payu on Setonix. It kinda sorta works with a few hacks that I haven't yet pushed to the repo given the very fragile nature of what we have done. The version @aidanheerdegen mentioned above was modified for the previous machine (Magus) at Pawsey. Since Pawsey switched to Setonix, we have started clean.

We haven't been using conda to manage payu. Instead, I've cloned it directly from the repo and have  a local, unpublished version

**Comment by aidanheerdegen** [comment]
> We haven't been using conda to manage payu. Instead, I've cloned it directly from the repo and have a local, unpublished version

Good to know, thanks. So I believe that means we're ok to move to publishing through the  [accessnri conda channel](https://anaconda.org/accessnri)

**Comment by dougiesquire** [comment]
Don't have permission to assign myself, but I can do this today at some point

**Comment by dougiesquire** [comment]
Someone with admin on both the payu repo and the accessnri conda channel will need to add an ANACONDA_TOKEN secret to the repo (👀 @aidanheerdegen)

**Comment by aidanheerdegen** [comment]
Note: To ensure CircleCI didn't keep trying to build removed access 

https://github.com/organizations/payu-org/settings/oauth_application_policy

![Screenshot 2023-06-08 at 9 47 40 am](https://github.com/payu-org/payu/assets/6063709/90ecccdb-a4d4-4bb3-8127-0cd33e8d0671)

Also removed TravisCI which is no longer used
