### ISSUE TITLE
archive link with ACCESS-OM3 driver

### ISSUE THREAD

**Issue by aekiss** [payu-org/payu#345]
It's a trivial cosmetic thing, but the ACCESS-OM3 driver makes archive links that look like this
`archive -> /./scratch/v45/aek156/access-om3/archive/MOM6-CICE6_ACCESS-OM3`
whereas the work link lacks the leading `/.` as it should:
`work -> /scratch/v45/aek156/access-om3/work/MOM6-CICE6_ACCESS-OM3`

**Comment by aidanheerdegen** [comment]
I'm guessing it is this logic:

https://github.com/payu-org/payu/blob/aacfd92570d6f33487ec4de47f9ad8b7a7fa8f12/payu/laboratory.py#L43-L46

but I'm not sure why it would apply in this case, unless when the symlink was created there was no `/scratch` directory visible?

Is it reproducible for all ACCESS-OM3 control directories?

**Comment by aekiss** [comment]
I just tried to reproduce this and couldn't, so I'll close this issue.
