### ISSUE TITLE
MVAPICH run option incompatible with submodels

### ISSUE THREAD

**Issue by aidanheerdegen** [payu-org/payu#350]
This logic

https://github.com/payu-org/payu/blob/aacfd92570d6f33487ec4de47f9ad8b7a7fa8f12/payu/experiment.py#L594-L596

is incompatible with submodels, as it would require doing an `os.chdir()` multiple times, with the final command running in the final submodel `work_path`. 

We're in the process of changing the logic for when `-wdir` is used, so just wanted to check we could get rid of this @marshallward

**Comment by marshallward** [comment]
I'm not using it so no problem from me.

(Looks very kludgy anyway, should be in a mpich-specific module?)

**Comment by aidanheerdegen** [comment]
This will likely be cleaned up when addressing #341

**Comment by aidanheerdegen** [comment]
> Looks very kludgy anyway, should be in a mpich-specific module?

Well as I said it doesn't support sub-models either, so regardless I don't think it is supportable in a general sense.

Looks like MPICH supports `-wdir` in any case, so we should just rip this out.
