### ISSUE TITLE
Remove payu from pypi?

### ISSUE THREAD

**Issue by aidanheerdegen** [payu-org/payu#361]
The `payu` version on pypi is very out of date, it is 0.5.1 and doesn't support `python3`

https://pypi.org/project/payu/

This isn't a massive problem IMO. As [previously discussed](https://github.com/payu-org/payu/issues/339) users either use the `conda` channel or self-install a modified version from source.

However it seems that recently it [did trip someone up](https://forum.access-hive.org.au/t/payu-issues-on-setonix/1333/5). 

So I think we should either remove it from `pypi`, or automatically publish to pypi from the CI. Removing it means losing the name on pypi, which if it was desirable to have in the future would be bad.

@marshallward you own the pypi project, so it's probably up to you.

**Comment by marshallward** [comment]
I think it's probably in your interest to keep the PyPI reference.  Even if things are mostly bundled under Conda these days, there is still value in supporting clean installs (or as much as it can be considered clean in Python).  Perhaps Payu is not there at the moment, but it's a good aspiration.

Also, given how short the name is, I doubt you'll ever get another chance to keep it :grin:.

But if you think its presence is a distraction then I would not want to interfere with that, so don't keep it on my account.

IMO the better solution is to follow your suggestion and do a PyPI update after each tag.  Even better if you're able to automate it.

Either way, I will assign you as an owner, @aidanheerdegen.  It doesn't make much sense for me to own it.
