### ISSUE TITLE
Read MOM6 parameter filenames from experiment in cesm_cmeps driver

### ISSUE THREAD

**Issue by dougiesquire** [payu-org/payu#371]
The same issue described in #325 is also in the `cesm_cmeps` driver:

https://github.com/payu-org/payu/blob/cfd694aa4744b1c7578e18a8993650df9bd88bfe/payu/models/cesm_cmeps.py#L26-L32

In addition, `field_table` (and possibly `data_table`??) needs to be added to the `"optional_config_files"` key.

**Comment by aidanheerdegen** [comment]
Seem to be talking about mixin classes a lot lately, but would this be a good case, move the logic @jo-basevi [just created](https://github.com/payu-org/payu/pull/364) to a mixin and inherit that in both models? Is there sufficient overlap of functionality?

**Comment by dougiesquire** [comment]
Sure - if it's possible to do this as a mixin, that would be great
