### ISSUE TITLE
Deployment fails with python >= 3.12

### ISSUE THREAD

**Issue by aidanheerdegen** [payu-org/payu#395]
The CD step deploying to conda fails due to a missing import `imp`

https://github.com/payu-org/payu/actions/runs/7382868756/job/20083209964#step:4:399

```
  ModuleNotFoundError: No module named 'imp'
  WARNING: Tests failed for payu-1.0.30-py_0.tar.bz2 - moving package to /usr/share/miniconda3/envs/test/conda-bld/broken
  TESTS FAILED: payu-1.0.30-py_0.tar.bz2
  export PREFIX=/usr/share/miniconda3/envs/test/conda-bld/payu_1704176755527/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
```

This appears to be a problem with python >= 3.12 due to that module being missing/deprecated

https://github.com/MultiQC/MultiQC/issues/2112

**Comment by aidanheerdegen** [comment]
This could have been avoided if the CI includes the conda package build steps, and CD just installs the produced artefact.

**Comment by CodeGat** [comment]
Would be keen to add the package build as a CI step as a later, non-bandaid solution. Right now, to get the releases out the door, pinning the version of Python used to `3.11` will be good enough.
