### ISSUE TITLE
payu --version not getting updated

### ISSUE THREAD

**Issue by anton-seaice** [payu-org/payu#401]
The payu version through the CLI is not getting updated with releases:

ie:
```
[as2285@gadi-login-07 as2285]$ payu --version
payu 1.0.19
[as2285@gadi-login-07 as2285]$ conda list | grep payu
payu                      1.0.29                    py_0    accessnri
```

**1.0.19 != 1.0.29**

See:

https://github.com/payu-org/payu/blob/ca0c825aaa1b228f1350f32b2318f40f29760aef/payu/__init__.py#L6

**Comment by aidanheerdegen** [comment]
Yeah, this is mentioned (though perhaps not explicitly enough) in this issue https://github.com/payu-org/payu/issues/398
