### ISSUE TITLE
Global config default stored in file

### ISSUE THREAD

**Issue by aidanheerdegen** [payu-org/payu#42]
Store all config.yaml defaults in a global config file.

This separates code from options and stores all defaults in one place, which makes it easy to find and update when required.

**Comment by marshallward** [comment]
currently the general approach is to check for a value. If none exists,
then try to guess the best value based on various factors.

I don't know if a default config file could ever capture all that.

But if it adds some value then I dint see the problem.

**Comment by aidanheerdegen** [comment]
I have come to the conclusion this is a bad idea. It makes it hard to track down errors and removes configuration from control directories/repos, which makes it hard to share and reproduce.
