### ISSUE TITLE
Mainfest `reproduce` options don't seem to do what they say on the box

### ISSUE THREAD

**Issue by dougiesquire** [payu-org/payu#456]
The [Payu docs say](https://payu.readthedocs.io/en/latest/config.html#manifests) that with the `manifest:reproduce:exe` flag set in the `config.yaml` Payu "will refuse to run if hashes do not match". This does not seem to happen. Instead Payu silently runs using the exectuables specified in the manifest.

Probsibly the same is true for `manifest:reproduce:input` and `manifest:reproduce:restart` - I haven't tested.

### To reproduce

Clone one of the [`access-om2-configs`](https://github.com/ACCESS-NRI/access-om2-configs) release branches (which all have `manifest:reproduce:exe = True`), modify an exectuable path in `config.yaml`, and run `payu setup` or `payu run`. Payu will behave as if no modifications were made to the `config.yaml`.

**Comment by aidanheerdegen** [comment]
I agree this is bad. I think it's my fault, and weirdly it was a conscious decision, but it does not match the documentation.

I was sure there was an existing issue for it, but I looked and couldn't find anything, so thanks for making one.
