### ISSUE TITLE
CABLE driver incompatible with CABLE-POP

### ISSUE THREAD

**Issue by Whyborn** [payu-org/payu#458]
The existing CABLE driver is specifically configured for the main branch of ```CABLE```, which is behind the ```CABLE-POP_TRENDY``` branch in terms of the physics. The ```CABLE-POP_TRENDY``` branch requires different namelists, and the existing CABLE driver is configured for a very specific set of meteorological forcings. To not break the existing ```benchcab``` configuration, a temporary new driver is required.

**Comment by aidanheerdegen** [comment]
You can add namelists to the optional namelists if they don't occur in both versions. MET forcings I don't know about, but sounds like they might have to be optional too?

**Comment by Whyborn** [comment]
This has been addressed as part of the larger work on the [staged_cable driver](https://github.com/payu-org/payu/pull/461).
