### ISSUE TITLE
Can readthedocs default to latest release tag ?

### ISSUE THREAD

**Issue by anton-seaice** [payu-org/payu#494]
Apologies for the unsolicited comments ...

Can read the docs default to showing latest release? rather than latest from main branch?

Also , when I select version (e.g. 1.1.5) it shows a strange commit at the top line of https://payu.readthedocs.io/en/1.1.5/:

> [payu 1.1.5+0.g78f67ff.dirty documentation](https://payu.readthedocs.io/en/1.1.5/#)

**Comment by jo-basevi** [comment]
Thanks for raising this issue! I've now changed `https://payu.readthedocs.io/` to default to `stable` which is the last released git tag (`https://payu.readthedocs.io/en/stable/`). The `latest` version still shows the code in the main branch (so it reflects what's in `payu/dev`).

The above PR hopefully will go towards fixing the strange commits..

**Comment by anton-seaice** [comment]
https://payu.readthedocs.io takes me to the stable version, and the header is correct now. It says _payu 1.1.6 documentation_ - thanks Jo!
