### ISSUE TITLE
Fix download-artifact workflow security warning

### ISSUE THREAD

**Issue by aidanheerdegen** [payu-org/payu#500]
We have a security warning for a workflow

https://github.com/payu-org/payu/security/dependabot?q=is%3Aopen+manifest%3A.github%2Fworkflows%2FCD.yml+package%3Aactions%2Fdownload-artifact

I don’t think it is a big risk, but should be simple to address.

**Comment by CodeGat** [comment]
This has been addressed by dependabot updating said file itself!
