### ISSUE TITLE
Support for cloning configurations from a git commit hash

### ISSUE THREAD

**Issue by minghangli-uni** [payu-org/payu#503]
I am wondering if Payu supports cloning a specific configuration directly from a git commit hash rather than from a branch? This feature would be helpful for reproducing experiments from precise commits in the repo's history.

**Comment by aidanheerdegen** [comment]
I don't believe it does, but it was something we identified as a missing capability when writing the payu training material.

@jo-basevi will look into it, and it shouldn't be too difficult to implement.
