### ISSUE TITLE
Checkout fails if PROJECT is not writeable

### ISSUE THREAD

**Issue by aidanheerdegen** [payu-org/payu#524]
While trying to repro the error reported here:

https://forum.access-hive.org.au/t/extending-access-om2-025-ryf-run-present-on-ik11/3689/11

`payu` errored with the `checkout` step because `project` is set in the `config.yaml`

https://github.com/rmholmes/025deg_jra55_ryf/blob/a29b0e442a791ef8ec04796fb6d3943aa3fc748f/config.yaml#L4

and the laboratory path is also set to an inaccessible project

https://github.com/rmholmes/025deg_jra55_ryf/blob/a29b0e442a791ef8ec04796fb6d3943aa3fc748f/config.yaml#L11

So when trying to checkout it throws this error:

```
$ payu checkout -r /g/data/ik11/outputs/access-om2-025/025deg_jra55_ryf9091_gadi/restart250/ -b new_branch_nam
e a29b0e4                                      
Created and checked out new branch: new_branch_name
laboratory path:  /scratch/e14/XXXXXX/access-om2
binary path:  /scratch/e14/XXXXXX/access-om2/bin
input path:  /scratch/e14/XXXXXX/access-om2/input
work path:  /scratch/e14/XXXXXX/access-om2/work
archive path:  /scratch/e14/XXXXXX/access-om2/archive
Updated metadata. Experiment UUID: 8e8fd75b-2a4f-4896-8fc2-702236bb4bad
Traceback (most recent call last):   
  File "/g/data/vk83/prerelease/apps/payu/dev/bin/payu", line 8, in <module>
    sys.exit(parse())           
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.10/site-packages/payu/cli.py", line 49, in parse
    run_cmd(**args)                            
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.10/site-packages/payu/subcommands/checkout_cmd.py", line 34, in runcmd
    checkout_branch(is_new_branch=new_branch,
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.10/site-packages/payu/branch.py", line 192, in checkout_branch
    metadata.write_metadata(set_template_values=True,
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.10/site-packages/payu/metadata.py", line 266, in write_metadata
    self.copy_to_archive()                     
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.10/site-packages/payu/metadata.py", line 347, in copy_to_archive
    mkdir_p(self.archive_path)       
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.10/site-packages/payu/fsops.py", line 41, in mkdir_p
    os.makedirs(path)           
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)          
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)                        
```

`payu checkout` should either check the user is a member of the project, or that the laboratory path is writeable.

It should probably fail with a useful error message, but also with instructions to recover from this error. 

In this case it was sufficient to remove the `project` and `laboratory` settings in `config.yaml` and then run `payu setup`. 

It errored on an inaccessible `input` path, but that is not related to the error above.

To repro:
```
git clone https://github.com/rmholmes/025deg_jra55_ryf my_new_example
cd my_new_example/
payu checkout -r /g/data/ik11/outputs/access-om2-025/025deg_jra55_ryf9091_gadi/restart250/ -b new_branch_name a29b0e4
git clone https://github.com/rmholmes/025deg_jra55_ryf my_new_example
cd my_new_example/
payu checkout -b new_branch_name ryf9091_gadi -r /g/data/ik11/outputs/access-om2-025/025deg_jra55_ryf9091_gadi/restart250/
```

**Comment by jo-basevi** [comment]
So payu uses the existence of archives to determine whether it should generate a new experiment UUID. So if the `payu checkout` exits with an error, and then `project` is fixed and a `payu setup` is run, it won't find any pre-existing archive directories so it'll assume it's a new experiment and generate a new experiment UUID and commit. I wonder if payu should probably prevent the commit from `payu checkout` if unable to create an `archive` as a new UUID will be generated at next `payu setup` anyway.

A fix I am working on so far, during checkout (after the git checkout has run), attempts to run `laboratory.initialise()`. If permission errors, log out a message and raise an error. (Could also run `os.access(laboratory.basepath, os.W_OK | os.X_OK)` to check for write permissions - <https://stackoverflow.com/a/2113511>). Then the log message could be something like:

```Failed to initialise laboratory directories.
Skipping creating metadata, restart configuration and setting up archive and work symlinks.
To fix the errors, edit one (or more) of the following config.yaml options that determine the laboratory path:
    - 'laboratory': (Top-level directory for the model laboratory - Default: /scratch/${PROJECT}/${USER}/${MODEL})
    - 'shortpath' (Top-level directory for laboratory - Default: /scratch/${PROJECT})
    - 'project': (The project to use for payu PBS jobs - Default: ${PROJECT})

Then either run:
- 'payu setup' or `payu checkout <CURRENT_BRANCH>` - if no experiment archive directory exists, it'll generate a new UUID.
- Or if starting from a restart, use  `payu checkout <CURRENT_BRANCH> -r <RESTART_PATH>`.
   As well as generating metadata and setting up symlinks, this will add a restart path to config.yaml and
   add parent experiment UUID to metadata file (if it exists).
```

I remember in the payu training session recently, people would checkout a branch of released configuration, then change `config.yaml` to a project that wasn't the default project in `config.yaml`, and then there were two commits for new UUIDs. Maybe project should be a command line option to `clone` and `checkout` commands? Though there is also `shortpath` and `laboratory` config options which both override `project`. So if project is defined would have to remove `shortpath` and `laboratory` from `config.yaml`.. (There's an existing a `--laboratory/--lab/-l` command-line option you can pass to `payu clone`/`payu checkout` which is only used to initialise the laboratory object during checkout. The configuration will still need to be changed before running `payu` commands or passing the laboratory to subsequent payu commands, e.g. `payu setup --lab <lab_path>`. So it's not exactly ideal but it is an option)
